discount_factor_g: 0.99
enable_double_dqn: true
enable_dueling_dqn: true
env_id: Walker2d-v5
epsilon_decay: 0.999995
epsilon_init: 1.0
epsilon_min: 0.01
learning_rate: 0.0001
mini_batch_size: 64
network_sync_rate: 2000
obs: pixel
replay_memory_size: 200000
